example1:
  name: "example1"
  installs:
    - flags:
        force: true
        source: "choco"
        quiet: true
        confirm: true
      packages:
        - git
        - vscode

example2:
  name: "example2"
  installs:
    - flags: {}
      packages:
        - git
    - flags:
        source: "winget"
      packages:
        - vscode
  actions:
    - name: command
      run: "echo Ciao"


gaming:
  name: "gaming"
  installs:
    - flags:
        version: "1.2.3"
      packages:
        - discord
    - flags:
      packages:
        - steam
        - gog
        - epicgames
  actions:
    - name: reboot
      run: "echo rebooting syste"
