example1:
  installs:
    - flags:
        force: true
        source: "choco"
        quiet: true
        confirm: true
      packages:
        - git
        - vscode

example2:
  installs:
    - packages:
        - git
    - flags:
        source: "winget"
      packages:
        - vscode
  uninstalls:
    - flags:
        source: "choco"
        confirm: true
        quiet: true
      packages:
        - some_package
  actions:
    - name: "command"
      run: "echo ciao"

example3:
  # uninstalls:
  #   - flags:
  #       source: "choco"
  #       confirm: true
  #       quiet: true
  #     packages:
  #       - bonjour
  #       - silverlight
  installs:
    - flags:
        confirm: true
        quiet: true
      packages:
        - bonjour
  actions:
    - name: "test1"
      run: "echo test uno"
    - name: "test2"
      run: "echo test due"

gaming:
  installs:
    - flags:
        version: "1.2.3"
      packages:
        - discord
    - packages:
        - steam
        - gog
        - epicgames
  actions:
    - name: "reboot"
      run: "echo rebooting system"
